#!/usr/bin/env bash
cd "$(dirname "$0")/../"


install-conf () {
    OLIVER=$PWD
    OLIVER_CONF="$OLIVER/conf/gitconfig"
    LOCAL_CONF="$HOME/.gitconfig"
    if [[ -L "${LOCAL_CONF}" ]]; then
        # remove any old symlinked confs
        rm "${LOCAL_CONF}"
    fi
    touch "$LOCAL_CONF"
    cat >> "$LOCAL_CONF" << __HERE__

[include]
    path = ${OLIVER_CONF}
__HERE__
}

install-completion () {
    curl \
        'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash' \
        -o ~/.git-completion.bash
}

install-all () {
    install conf
    install completion
}


install () {
    for arg in $@; do
        echo "# vim: install - ${arg}"
        "install-${arg}"
    done
}

$@
