#!/usr/bin/env bash
cd "$(dirname "$0")/../"

set -eu


USER='oliver-sanders'


CYLC_REPOS=(\
    cylc-admin
    cylc-examples
    cylc
    cylc-graphic-design
    cylc-sphinx-extensions
    cylc-ui
    cylc-uiserver
    cylc-xtriggers
    isodatetime
    presentations
    rose
)


UPSTREAMS=(\
    cylc
    metomi
)


declare -A USERS
USERS=(\
    [mel]=datamel
    [dave]=dpmatthews
    [david]=dwsutherland
    [hillary]=hjoliver
    [bruno]=kinow
    [ronnie]=metronnie
    [tim]=wxtim
)


set-upstream () {
    REPO="$1"
    REPO_DIR="${HOME}/${REPO}"
    if git -C "${REPO_DIR}" remote -v | grep -q upstream; then
        return  # upstream already set -> skip
    fi
    for upstream in "${UPSTREAMS[@]}"; do
        if curl --fail "https://github.com/${upstream}/${REPO}" >/dev/null 2>&1;
        then
            git -C "${REPO_DIR}" remote add \
                upstream \
                "git@github.com:${upstream}/${REPO}.git"
            return
        fi
    done
}


set-remotes () {
    REPO="$1"
    REPO_DIR="${HOME}/${REPO}"
    for name in "${!USERS[@]}"; do
        user="${USERS[$name]}"
        git -C "${REPO_DIR}" remote remove $name
        git -C "${REPO_DIR}" remote add \
            "${name}" \
            "https://github.com/${user}/${REPO}"
    done
}


install-cylc () {
    for repo in "${CYLC_REPOS[@]}"; do
        install-repo "$repo"
    done 
}


install-repo() {
    REPO="$1"
    REPO_DIR="${HOME}/${REPO}"
    if ! [[ -d "${REPO_DIR}" ]]; then
        git clone "git@github.com:${USER}/${REPO}.git" "${REPO_DIR}"
    fi
    set-upstream "${REPO}"
    set-remotes "${REPO}"
}


install-all () {
    install cylc
}

install () {
    for arg in $@; do
        echo "# conda: install - ${arg}"
        "install-${arg}"
    done
}

$@
