#!/usr/bin/env bash
cd "$(dirname "$0")/../"

install-bashrc () {
    if ! grep '.oliver/conf/bashrc' ~/.bashrc -q ; then
        echo '. "$HOME/.oliver/conf/bashrc"' >> "$HOME/.bashrc"
    fi
}

install-inputrc () {
    if [[ ! -L "$HOME/.inputrc" ]]; then
        (
            cd "$HOME"
            ln -s "$HOME/.oliver/conf/inputrc" ".inputrc"
        )
    fi
}

install-vim () {
    sbin/install-vim install all
}

install-all () {
    install bashrc
    install vim
    install inputrc
}

install () {
    for arg in $@; do
        echo "# install - ${arg}"
        "install-${arg}"
    done
}

$@
