#!/bin/bash
cd "$(dirname "$0")/../"

VIM_DIR="$HOME/.vim"

install-vundle () {
    if [[ ! -d $HOME/.vim/bundle/Vundle.vim  ]]; then
        git clone \
            'https://github.com/VundleVim/Vundle.vim.git' \
            "$VIM_DIR/bundle/Vundle.vim"
    fi
}

install-vimrc () {
    cp conf/vimrc "$HOME/.vimrc"
}

install-packages () {
    vim +BundleInstall +qall
}

install-all () {
    install vundle
    install vimrc
    install packages
}

install () {
    for arg in $@; do
        echo "# vim: install - ${arg}"
        "install-${arg}"
    done
}

$@
