#!/usr/bin/env bash
cd "$(dirname "$0")/../"


install-conf () {
    OLIVER=$PWD
    (
        cd $HOME
        ln -s $OLIVER/conf/gitconfig .gitconfig
    )
}

install-completion () {
    curl \
        'https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash' \
        -o ~/.git-completion.bash
}

install-all () {
    install conf
    install completion
}


install () {
    for arg in $@; do
        echo "# vim: install - ${arg}"
        "install-${arg}"
    done
}

$@
