#!/usr/bin/env bash
cd "$(dirname "$0")/../"

VIM_DIR="$HOME/.vim"

install-vundle () {
    if [[ ! -d $HOME/.vim/bundle/Vundle.vim  ]]; then
        git clone \
            'https://github.com/VundleVim/Vundle.vim.git' \
            "$VIM_DIR/bundle/Vundle.vim"
    fi
}

install-vimrc () {
    (
        cd "$HOME"
        rm '.vimrc'
        ln -s '.oliver/conf/vimrc' '.vimrc'
    )
}

install-packages () {
    vim +BundleInstall +qall
}

install-conda-env () {
    mamba env remove -n vim
    mamba env create -n vim -f "$HOME/.oliver/env/vim.yml"
}

install-all () {
    install vundle
    install vimrc
    install packages
    install conda-env
}

install () {
    for arg in $@; do
        echo "# vim: install - ${arg}"
        "install-${arg}"
    done
}

$@
