#!/usr/bin/env bash
cd "$(dirname "$0")/../"

CONDA_DIR="${HOME}/mambaforge/"

download-conda-darwin () {
    curl \
        https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-x86_64.sh
        -o "$1"
}

download-conda-linux () {
    curl \
        https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
        -o "$1"
}

install-conda () {
    if ! [[ -d "${CONDA_DIR}" ]]; then
        CONDA_INSTALL="$(mktemp)"
        if [[ "$OSTYPE" == darwin* ]]; then
            download-conda-darwin "${CONDA_INSTALL}"
        elif [[ "$OSTYPE" == "linux-gnu" ]]; then
            download-conda-linux "${CONDA_INSTALL}"
        else
            echo "Cannot install Conda for $OSTYPE" >&2
            exit 1
        fi
        bash "${CONDA_INSTALL}" -h
        rm "${CONDA_INSTALL}"
    fi
}

install-all () {
    install conda
}

install () {
    for arg in $@; do
        echo "# conda: install - ${arg}"
        "install-${arg}"
    done
}

$@
